dev_croix_rouge/urls.py
from django.contrib import admin
from django.urls import path, include

from CoronApp.views import *

urlpatterns = [
    # Administration
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    # Demandes
    path("demandes/", ListDemandes.as_view(), name="demandes"),
    path("demande/<pk>", DemandeView.as_view(), name="demande"),
    path("demande/<pk>/edit", DemandeEditView.as_view(), name="demande-edit"),
    path("newdemande/", DemandeFormView.as_view(), name="demande-form"),
    # Assignations
    path("demande/<pk>/assign/<t>", assign_view, name="assign"),
    path(
        "demande/<pk>/affecter_ressource", affecter_ressource, name="affecter-ressource"
    ),
    path(
        "demande/<pk>/desaffecter_ressource",
        desaffecter_ressource,
        name="desaffecter-ressource",
    ),
    path("demande/<pk>/assign_ressource", set_assign, name="assign-ressource"),
    path("demande/<pk>/finir_assignation", finir_assignation, name="finir-assignation"),
    path(
        "demande/<pk>/enregistrer_commentaire_assignation",
        enregistrer_commentaire_assignation,
        name="enregistrer_commentaire_assignation",
    ),
    # Opérations sur les demandes
    path("demande/<pk>/cloture", cloture, name="cloture"),
    path("demande/<pk>/validate", validate, name="validate"),
    path("demande/<pk>/archive", archive, name="archive"),
    path("demande/<pk>/refuse", refuse, name="refuse"),
    path("demande/<pk>/retour", RetourView.as_view(), name="retour-form"),
    # Impports
    path("imports", imports_view, name="imports"),
    # Page d'acceuil
    path("", index),
]

CoronApp/models/demande.py
import sys

from django.conf import settings
from django.db import models
from django.utils.html import format_html
from django_fsm import FSMField, transition

from . import reservation
from .profil import Profil
from .retour import *
from .reponse import Reponse

ETATS = {
    ("cree", "Créée"),
    ("valide", "Validée"),
    ("provisionne", "Provisionnée"),
    ("cloture", "Cloturée"),
    ("refuse", "Refusée"),
    ("termine", "Terminée"),
    ("archive", "Archivée"),
}

TYPES = {
    ("logistique", "Logistique"),
    ("maraude", "Maraude sanitaire"),  # Demande particulière
    ("aide_alim", "Aide alimentaire"),  # Demande partiulière
    ("colis_urgence", "Colis d'urgence"),  # Demande particulière
    ("cr_chez_vous", "Croix-Rouge chez vous"),
    ("mission_urgence", "Mission d'urgence"),
    ("accueil_jour", "Accueil de jour"),
    ("secours_publics", "Renfort secours publics"),
    ("desserrement", "Centre de desserrement"),
    ("distribution", "Distribution alimentaire"),  # Demande particulière
    ("continuite", "Continuité des activités"),  # Pas de retour particulier
    ("accueil_ecoute", "Accueil-écoute"),  # Pas de retour particulier
    ("soutien_op", "Soutien à l'opération"),  # Pas de retour particulier
    ("non_defini", "Non précisé"),  # Default
}


class Demande(models.Model):
    class Meta:
        ordering = ["date_debut", "responsable", "titre"]
        permissions = [
            ("can_validate", "Can validate request"),
            ("can_cloture", "Can cloture"),
            ("can_edit", "Can edit a demand"),
            ("can_refuse", "Can refuse a demand"),
            ("can_finish", "Can add feedback"),
            ("can_archive", "Can archive demande"),
        ]

    created_at = models.DateTimeField(
        verbose_name="Date de création de la demande", auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name="Date de dernière édition", auto_now=True
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL
    )
    etat = FSMField(default="cree", choices=ETATS)

    # Infos générales

    titre = models.CharField(verbose_name="Titre de la demande", max_length=128)
    date_debut = models.DateTimeField(
        verbose_name="Date et heure de début de l'opération"
    )
    date_fin = models.DateTimeField(verbose_name="Date et heure de fin de l'opération")
    lieu_deroulement = models.CharField(
        verbose_name="Lieu de la mission", max_length=255
    )
    responsable = models.ForeignKey(
        Profil,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Responsable de la mission",
    )
    type = models.CharField(
        verbose_name="Type de mission",
        choices=TYPES,
        default="non_defini",
        max_length=100,
    )

    # Effectifs
    nb_benevoles = models.PositiveIntegerField(
        verbose_name="Nombre de bénévoles demandés", default=0
    )
    date_presence_debut = models.DateTimeField(
        verbose_name="Date et heure du rendez-vous pour les bénévoles"
    )
    date_presence_fin = models.DateTimeField(
        verbose_name="Date et heure de fin de présence pour la mission"
    )
    lieu_rdv = models.CharField(
        verbose_name="Lieu de rendez-vous pour les bénévoles", max_length=255
    )
    qualifications = models.TextField(
        verbose_name="Qualifications spécifiques demandées", blank=True
    )

    # Subsistances
    nb_repas = models.PositiveIntegerField(
        verbose_name="Nombre de repas nécessaires", default=0
    )
    lieu_repas = models.CharField(
        verbose_name="Lieu de la prise de repas", max_length=255, blank=True
    )
    commentaires_repas = models.TextField(
        verbose_name="Commentaires/Régimes alimentaires particuliers", blank=True
    )

    # Vehicules
    nb_transport = models.PositiveIntegerField(
        verbose_name="Bénévoles à transporter", default=0
    )
    nb_log = models.PositiveIntegerField(verbose_name="Nombre de LOG", default=0)
    nb_vl = models.PositiveIntegerField(verbose_name="Nombre de VL", default=0)
    nb_vpsp = models.PositiveIntegerField(verbose_name="Nombre de VPSP", default=0)
    commentaire_transport = models.TextField(
        verbose_name="Demande spécifique", blank=True
    )

    # Logistique
    nature_chargement = models.CharField(
        verbose_name="Nature du chargement",
        help_text="Taille, poids, conditionnement",
        max_length=255,
        blank=True,
    )
    est_alimentaire = models.BooleanField(
        verbose_name="Contient de l'alimentaire", default=False
    )
    est_frais = models.BooleanField(verbose_name="Frais", default=False)
    moyens_engages = models.TextField(
        verbose_name="Moyens engagés",
        help_text="[type, nombre, utilisation], [secours, urgence (CAI/CHU/etc.), électriques ("
        "chauffage/GPE/rallonges/lampes/etc.), soutien (tables/chaise/etc.)]",
        blank=True,
    )

    # Infos complémentaires
    contact_in_situ = models.CharField(
        verbose_name="Contact sur place", max_length=255, blank=True
    )
    tel_in_situ = models.CharField(
        verbose_name="Téléphone du contact sur place", max_length=20, blank=True
    )
    description_detaillee = models.TextField(
        verbose_name="Description détaillée de la mission",
        help_text="Chronogramme précis, transport, mise en place etc.",
    )

    # Infos spécifique à un type de demande
    # Pas de classes dérivées pour les demandes spécifiques parce que ce serait trop compliqué pour la suite,
    # les infos sont juste blank sinon, vu le volume de données c'est pas trop gros
    # Pour les retours en revanche on utilise de la composition

    # Maraude sanitaire
    nb_PASS = models.PositiveIntegerField(
        verbose_name="Nombre total de personnel PASS", blank=True, default=0
    )

    # Aide alimentaire
    nb_colis = models.PositiveIntegerField(
        verbose_name="Nombre de colis d'urgence", blank=True, default=0
    )

    # Colis d'urgence
    nb_beneficiaire_h = models.PositiveIntegerField(
        verbose_name="Nombre de bénéficiaires homme", blank=True, default=0
    )
    nb_beneficiaire_f = models.PositiveIntegerField(
        verbose_name="Nombre de bénéficiaires femme", blank=True, default=0
    )
    nb_beneficiaire_enfant = models.PositiveIntegerField(
        verbose_name="Nombre de bénéficiaires enfant", blank=True, default=0
    )
    eau_potable = models.BooleanField(
        verbose_name="Accès eau potable", blank=True, default=False
    )
    frigo = models.BooleanField(
        verbose_name="Présence de frigo", blank=True, default=False
    )
    cuisiner = models.BooleanField(
        verbose_name="Possibilité de cuisiner", blank=True, default=False
    )
    risque_sanitaire = models.TextField(verbose_name="Risque sanitaire", blank=True)

    # Distribution alimentaire
    nb_colis_type_1 = models.PositiveIntegerField(
        verbose_name="Nombre de colis de type 1", blank=True, default=0
    )
    nb_colis_type_2 = models.PositiveIntegerField(
        verbose_name="Nombre de colis de type 2", blank=True, default=0
    )
    nb_colis_type_3 = models.PositiveIntegerField(
        verbose_name="Nombre de colis de type 3", blank=True, default=0
    )
    nb_beneficiaire = models.PositiveIntegerField(
        verbose_name="Nombre de bénéficiaires", blank=True, default=0
    )
    typologie_beneficiaire = models.TextField(
        verbose_name="Typologie des bénéficiaires", blank=True
    )

    # Propriétée utilisée dans l'admin Django pour colorer les états des demandes
    def colored_etat(self):
        return format_html(
            '<span class="color_{}">{}</span>', self.etat, self.get_etat_display()
        )

    colored_etat.short_description = "Etat"

    @transition(
        field=etat,
        source="cree",
        target="valide",
        permission=lambda instance, user: user.hasPerm("CoronApp.can_validate"),
    )
    def validate(self):
        r = Reponse(demande=self)
        r.save()

    def est_provisionne(self):
        if (
            self.reponse.effectifs_provisionnes
            and self.reponse.logistique_provisionnes
            and self.reponse.subsistances_provisionnes
            and self.reponse.vehicules_provisionnes
        ):
            return True
        return False

    @transition(
        field=etat, source="valide", target="provisionne", conditions=[est_provisionne]
    )
    def provisionne(self):
        pass

    @transition(field=etat, source="cree", target="refuse")
    def refuse(self):
        pass

    @transition(
        field=etat,
        source="provisionne",
        target="cloture",
        permission=lambda instance, user: user.hasPerm("CoronApp.can_cloture"),
    )
    def cloture(self):
        ret = Retour(demande=self)
        ret.save()

    @transition(field=etat, source="cloture", target="termine")
    def termine(self):
        pass

    @transition(field=etat, source=["termine", "cloture", "refuse"], target="archive")
    def archive(self):
        pass

    def has_retour_spe(self):
        """ Seuls quelques types de mission n'ont pas de retour spéciique, cette fonction sert pour le template
        et retourne vrai si la demande a une retour spécifique
        """

        return self.type not in [
            "non_defini",
            "continuite",
            "accueil_ecoute",
            "soutien_op",
        ]

    def has_demande_spe(self):
        """ Idem du côté de la demande spécifique : 4 types ont des spécificités """
        return self.type in ["maraude", "aide_alim", "colis_urgence", "distribution"]

    def __str__(self):
        return "Demande " + self.titre

templates/demande/detail-demande.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        {% include 'demande/detail/detail-header.html' %}

        <!-- Conteneur principal du détail de la mission -->
        <div class="border container" class="col-md-8" , style="padding: 20px;">
            {% include 'demande/detail/detail-demande.html' %}

            {% if  demande.etat != cree %}
                {% if demande.reponse %}
                    {% include 'demande/detail/detail-assignations.html' %}

                    {% if demande.etat == "cloture" or demande.etat == "termine" or demande.etat == "archive"%}
                        {% include 'demande/detail/detail-retour.html' %}
                        {% include 'demande/detail/detail-retour-spe.html' %}
                    {% endif %}

                    <div class="text-center">
                        <button type="button" class="btn btn-success m-4" onclick="window.print();return false;">
                            Télécharger/Imprimer
                        </button>
                    </div>

                {% endif %}
            {% endif %}

        </div>
    </div>

{% endblock %}

templates/demande/form-demande.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="title">
        <h2 class="text-center">Demande de moyens</h2>
        <h3 class="text-center">Opération COVID-19 | Délégation Territoriale du Rhône</h3>
    </div>
    <div class="col-md-10 offset-md-1">
        {% crispy form %}
    </div>

    <script>
        $(function () {
            $('#id_titre').focus();

            const idType = $("#id_type");
            $('.optional').hide();
            $('.optional#' + idType.val()).show();

            idType.change(function () {
                $('.optional').hide();
                $('.optional#' + $('#id_type').val()).show('fast');
            });

            // setup previous and next buttons
            $('#button-id-previous').click(() => {
                $(".nav-tabs .active").parent().prev("li").find('a').click();
            });

            $('#button-id-next').click(() => {
                $(".nav-tabs .active").parent().next("li").find('a').click();
            });

            $('.datetime-input').datetimepicker({
                format: 'd/m/Y H:i',
                lang: 'fr',
            });

            // Synchro des dates de début et de fin pour le rendez -vous et pour la mission
            $('#id_date_debut').change(()=> {
                $("#id_date_presence_debut").val($("#id_date_debut").val());
            })

            $('#id_date_fin').change(()=> {
                $("#id_date_presence_fin").val($("#id_date_fin").val());
            })

            // setup tab form check
            const form = $('#demande-form');
            const submitButton = form.find('input[type="submit"]');
            const requiredInputs = form.find('input[required],select[required],textarea[required]');
            // pre compute the tab associated with each input
            const tabs = {};
            const idxToTab = requiredInputs.map((i, input) => {
                const inputJquery = $(input);
                const tabId = inputJquery.parents('.tab-pane').prop('id');
                if(!tabs.hasOwnProperty(tabId)) {
                    tabs[tabId] = {
                        $: inputJquery
                                .parents('.tab-content')
                                .siblings('.nav-tabs')
                                .find('a[href="#' + tabId + '"]'),
                        valid: true
                    };
                }
                return tabId;
            }).get();
            submitButton.hide();

            const checkForm = () => {
                // reset tab validity
                let allValid = true;
                Object.keys(tabs).forEach(k => tabs[k].valid = true);

                // check every field
                for(let i = 0; i < requiredInputs.length; i++) {
                    if(!requiredInputs[i].checkValidity()) {
                        allValid = false;
                        tabs[idxToTab[i]].valid = false;
                    }
                }

                // apply css class accordingly
                Object.keys(tabs).forEach(k => {
                    if(tabs[k].valid)
                        tabs[k].$.removeClass('invalid-form-tab');
                    else
                        tabs[k].$.addClass('invalid-form-tab');
                });

                if(allValid)
                    submitButton.show();
                else
                    submitButton.hide();
            };

            requiredInputs.on("input", checkForm);

            // trigger check immediately
            checkForm();
        });
    </script>
{% endblock %}

templates/demande/form-edit-demande.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <script type="application/javascript">
        window.addEventListener("DOMContentLoaded", (event) => {
            $('#id_titre').focus();
        });
    </script>
    <div class="title">
        <h2 class="text-center">Edition de la mission {{ demande.titre }}</h2>
    </div>
    <div class="col-md-10 offset-md-1">
        {% if demande.etat != 'cree' %}
            <div style="color: #7a000f">Note : l'édition des dates de la mission et du rendez-vous n'est plus possible
                après la validation. Créez une nouvelle demande pour modifier les dates.
            </div>
        {% endif %}

        {% crispy form %}

    </div>

    <script>
        $(document).ready(function () {
            // Les datetimeinput sont désactivés, on ne change pas le curseur
            {% if demande.etat != 'cree' %}
                $('.datetimeinput').prop('style', 'pointer-events:none;');
            {% else %}
                $('.datetime-input').datetimepicker({
                    format: 'd/m/Y H:i',
                    lang: 'fr',
                });
            {% endif %}

            // Cache les infos qui ne concernent pas le type spécifique de mission
            $('.optional').hide();
            $('.optional#' + $('#id_type').val()).show();
        })

        $('#id_type').change(function () {
            $('.optional').hide();
            $('.optional#' + $('#id_type').val()).show('fast');
        });

        // setup previous and next buttons
        $('#button-id-previous').click(() => {
            $(".nav-tabs .active").parent().prev("li").find('a').click();
        });

        $('#button-id-next').click(() => {
            $(".nav-tabs .active").parent().next("li").find('a').click();
        });
    </script>
{% endblock %}

templates/demande/form-retour.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edition du retour de mission{% endblock %}

{% block content %}
    <div class="title">
        <h2 class="text-center">Retour de mission</h2>
    </div>
    <div class="col-md-6 offset-md-3">
        <form action="{% url 'retour-form' id_dde %}" method="POST">
            {% crispy retourForm retourForm.helper %}
            {% crispy retourFormSpe retourFormSpe.helper %}

            <div class="form-action">
                <input type="submit" name="submit" value="Envoyer" class="btn btn-primary float-right">
            </div>
        </form>
    </div>
{% endblock %}

templates/demande/list-demandes.html
{% extends 'base.html' %}
{% block content %}
    <div class="title">
        <h2 class="text-center">Gestion des demandes</h2>
    </div>
    <div class="col-md-10 offset-md-1" style="text-align: center;">
        <table id="table_id" class="display">
            <thead>
            <tr>
                <th>Date</th>
                <th>Mission</th>
                <th>Type</th>
                <th>Responsable</th>
                <th>Etat</th>
                <th>Gérer</th>
            </tr>
            </thead>

            <tbody>
            {% for demande in demandes %}
                <tr>
                    <!-- data-order : pour trier correctement par date-->
                    <td data-order="{{ demande.date_debut|date:"Y-m-d H:i" }}">{{ demande.date_debut|date:"d/m/y H:i" }}</td>
                    <td>{{ demande.titre }}</td>
                    <td><span
                            class="badge badge-pill badge-secondary">{% firstof demande.get_type_display "indéfini" %}</span>
                    </td>
                    <td>{{ demande.responsable }}</td>
                    <td class="color_{{ demande.etat }}"><b>{{ demande.get_etat_display }}</b></td>
                    <td>
                        <button onclick="window.location='{% url 'demande' demande.id %}'"
                                class="btn btn-outline-primary">Détails
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>

            <thead>
            <tr>
                <th>Date</th>
                <th>Mission</th>
                <th>Type</th>
                <th>Responsable</th>
                <th>Etat</th>
                <th>Gérer</th>
            </tr>
            </thead>

        </table>
    </div>

    <script>
        $(document).ready(function () {
            setTimeout(function () {
                location.reload();
            },350000)
            $('#table_id').DataTable({
                "order": [[0, "desc"]], // Tri en fonction de la date par défaut, avec les missions les plus récentes en haut
                aLengthMenu: [
                    [25, 50, -1],
                    [25, 50, "Tout"]
                ],
                language: {
                    processing: "Traitement en cours...",
                    search: "Rechercher&nbsp;:",
                    lengthMenu: "Afficher _MENU_ &eacute;l&eacute;ments",
                    info: "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                    infoEmpty: "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                    infoFiltered: "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                    infoPostFix: "",
                    loadingRecords: "Chargement en cours...",
                    zeroRecords: "Aucun &eacute;l&eacute;ment &agrave; afficher",
                    emptyTable: "Aucune donnée disponible dans le tableau",
                    paginate: {
                        first: "Premier",
                        previous: "Pr&eacute;c&eacute;dent",
                        next: "Suivant",
                        last: "Dernier"
                    },
                    aria: {
                        sortAscending: ": activer pour trier la colonne par ordre croissant",
                        sortDescending: ": activer pour trier la colonne par ordre décroissant"
                    }
                }
            });
        });
    </script>
{% endblock %}