dev_croix_rouge/urls.py
from django.contrib import admin
from django.urls import path, include

from CoronApp.views import *

urlpatterns = [
    # Administration
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    # Demandes
    path("demandes/", ListDemandes.as_view(), name="demandes"),
    path("demande/<pk>", DemandeView.as_view(), name="demande"),
    path("demande/<pk>/edit", DemandeEditView.as_view(), name="demande-edit"),
    path("newdemande/", DemandeFormView.as_view(), name="demande-form"),
    # Assignations
    path("demande/<pk>/assign/<t>", assign_view, name="assign"),
    path(
        "demande/<pk>/affecter_ressource", affecter_ressource, name="affecter-ressource"
    ),
    path(
        "demande/<pk>/desaffecter_ressource",
        desaffecter_ressource,
        name="desaffecter-ressource",
    ),
    path("demande/<pk>/assign_ressource", set_assign, name="assign-ressource"),
    path("demande/<pk>/finir_assignation", finir_assignation, name="finir-assignation"),
    path(
        "demande/<pk>/enregistrer_commentaire_assignation",
        enregistrer_commentaire_assignation,
        name="enregistrer_commentaire_assignation",
    ),
    # Opérations sur les demandes
    path("demande/<pk>/cloture", cloture, name="cloture"),
    path("demande/<pk>/validate", validate, name="validate"),
    path("demande/<pk>/archive", archive, name="archive"),
    path("demande/<pk>/refuse", refuse, name="refuse"),
    path("demande/<pk>/retour", RetourView.as_view(), name="retour-form"),
    # Impports
    path("imports", imports_view, name="imports"),
    # Page d'acceuil
    path("", index),
]

CoronApp/models/demande.py
import sys

from django.conf import settings
from django.db import models
from django.utils.html import format_html
from django_fsm import FSMField, transition

from . import reservation
from .profil import Profil
from .retour import *
from .reponse import Reponse

ETATS = {
    ("cree", "Créée"),
    ("valide", "Validée"),
    ("provisionne", "Provisionnée"),
    ("cloture", "Cloturée"),
    ("refuse", "Refusée"),
    ("termine", "Terminée"),
    ("archive", "Archivée"),
}

TYPES = {
    ("logistique", "Logistique"),
    ("maraude", "Maraude sanitaire"),  # Demande particulière
    ("aide_alim", "Aide alimentaire"),  # Demande partiulière
    ("colis_urgence", "Colis d'urgence"),  # Demande particulière
    ("cr_chez_vous", "Croix-Rouge chez vous"),
    ("mission_urgence", "Mission d'urgence"),
    ("accueil_jour", "Accueil de jour"),
    ("secours_publics", "Renfort secours publics"),
    ("desserrement", "Centre de desserrement"),
    ("distribution", "Distribution alimentaire"),  # Demande particulière
    ("continuite", "Continuité des activités"),  # Pas de retour particulier
    ("accueil_ecoute", "Accueil-écoute"),  # Pas de retour particulier
    ("soutien_op", "Soutien à l'opération"),  # Pas de retour particulier
    ("non_defini", "Non précisé"),  # Default
}


class Demande(models.Model):
    class Meta:
        ordering = ["date_debut", "responsable", "titre"]
        permissions = [
            ("can_validate", "Can validate request"),
            ("can_cloture", "Can cloture"),
            ("can_edit", "Can edit a demand"),
            ("can_refuse", "Can refuse a demand"),
            ("can_finish", "Can add feedback"),
            ("can_archive", "Can archive demande"),
        ]

    created_at = models.DateTimeField(
        verbose_name="Date de création de la demande", auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name="Date de dernière édition", auto_now=True
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL
    )
    etat = FSMField(default="cree", choices=ETATS)

    # Infos générales

    titre = models.CharField(verbose_name="Titre de la demande", max_length=128)
    date_debut = models.DateTimeField(
        verbose_name="Date et heure de début de l'opération"
    )
    date_fin = models.DateTimeField(verbose_name="Date et heure de fin de l'opération")
    lieu_deroulement = models.CharField(
        verbose_name="Lieu de la mission", max_length=255
    )
    responsable = models.ForeignKey(
        Profil,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Responsable de la mission",
    )
    type = models.CharField(
        verbose_name="Type de mission",
        choices=TYPES,
        default="non_defini",
        max_length=100,
    )

    # Effectifs
    nb_benevoles = models.PositiveIntegerField(
        verbose_name="Nombre de bénévoles demandés", default=0
    )
    date_presence_debut = models.DateTimeField(
        verbose_name="Date et heure du rendez-vous pour les bénévoles"
    )
    date_presence_fin = models.DateTimeField(
        verbose_name="Date et heure de fin de présence pour la mission"
    )
    lieu_rdv = models.CharField(
        verbose_name="Lieu de rendez-vous pour les bénévoles", max_length=255
    )
    qualifications = models.TextField(
        verbose_name="Qualifications spécifiques demandées", blank=True
    )

    # Subsistances
    nb_repas = models.PositiveIntegerField(
        verbose_name="Nombre de repas nécessaires", default=0
    )
    lieu_repas = models.CharField(
        verbose_name="Lieu de la prise de repas", max_length=255, blank=True
    )
    commentaires_repas = models.TextField(
        verbose_name="Commentaires/Régimes alimentaires particuliers", blank=True
    )

    # Vehicules
    nb_transport = models.PositiveIntegerField(
        verbose_name="Bénévoles à transporter", default=0
    )
    nb_log = models.PositiveIntegerField(verbose_name="Nombre de LOG", default=0)
    nb_vl = models.PositiveIntegerField(verbose_name="Nombre de VL", default=0)
    nb_vpsp = models.PositiveIntegerField(verbose_name="Nombre de VPSP", default=0)
    commentaire_transport = models.TextField(
        verbose_name="Demande spécifique", blank=True
    )

    # Logistique
    nature_chargement = models.CharField(
        verbose_name="Nature du chargement",
        help_text="Taille, poids, conditionnement",
        max_length=255,
        blank=True,
    )
    est_alimentaire = models.BooleanField(
        verbose_name="Contient de l'alimentaire", default=False
    )
    est_frais = models.BooleanField(verbose_name="Frais", default=False)
    moyens_engages = models.TextField(
        verbose_name="Moyens engagés",
        help_text="[type, nombre, utilisation], [secours, urgence (CAI/CHU/etc.), électriques ("
        "chauffage/GPE/rallonges/lampes/etc.), soutien (tables/chaise/etc.)]",
        blank=True,
    )

    # Infos complémentaires
    contact_in_situ = models.CharField(
        verbose_name="Contact sur place", max_length=255, blank=True
    )
    tel_in_situ = models.CharField(
        verbose_name="Téléphone du contact sur place", max_length=20, blank=True
    )
    description_detaillee = models.TextField(
        verbose_name="Description détaillée de la mission",
        help_text="Chronogramme précis, transport, mise en place etc.",
    )

    # Infos spécifique à un type de demande
    # Pas de classes dérivées pour les demandes spécifiques parce que ce serait trop compliqué pour la suite,
    # les infos sont juste blank sinon, vu le volume de données c'est pas trop gros
    # Pour les retours en revanche on utilise de la composition

    # Maraude sanitaire
    nb_PASS = models.PositiveIntegerField(
        verbose_name="Nombre total de personnel PASS", blank=True, default=0
    )

    # Aide alimentaire
    nb_colis = models.PositiveIntegerField(
        verbose_name="Nombre de colis d'urgence", blank=True, default=0
    )

    # Colis d'urgence
    nb_beneficiaire_h = models.PositiveIntegerField(
        verbose_name="Nombre de bénéficiaires homme", blank=True, default=0
    )
    nb_beneficiaire_f = models.PositiveIntegerField(
        verbose_name="Nombre de bénéficiaires femme", blank=True, default=0
    )
    nb_beneficiaire_enfant = models.PositiveIntegerField(
        verbose_name="Nombre de bénéficiaires enfant", blank=True, default=0
    )
    eau_potable = models.BooleanField(
        verbose_name="Accès eau potable", blank=True, default=False
    )
    frigo = models.BooleanField(
        verbose_name="Présence de frigo", blank=True, default=False
    )
    cuisiner = models.BooleanField(
        verbose_name="Possibilité de cuisiner", blank=True, default=False
    )
    risque_sanitaire = models.TextField(verbose_name="Risque sanitaire", blank=True)

    # Distribution alimentaire
    nb_colis_type_1 = models.PositiveIntegerField(
        verbose_name="Nombre de colis de type 1", blank=True, default=0
    )
    nb_colis_type_2 = models.PositiveIntegerField(
        verbose_name="Nombre de colis de type 2", blank=True, default=0
    )
    nb_colis_type_3 = models.PositiveIntegerField(
        verbose_name="Nombre de colis de type 3", blank=True, default=0
    )
    nb_beneficiaire = models.PositiveIntegerField(
        verbose_name="Nombre de bénéficiaires", blank=True, default=0
    )
    typologie_beneficiaire = models.TextField(
        verbose_name="Typologie des bénéficiaires", blank=True
    )

    # Propriétée utilisée dans l'admin Django pour colorer les états des demandes
    def colored_etat(self):
        return format_html(
            '<span class="color_{}">{}</span>', self.etat, self.get_etat_display()
        )

    colored_etat.short_description = "Etat"

    @transition(
        field=etat,
        source="cree",
        target="valide",
        permission=lambda instance, user: user.hasPerm("CoronApp.can_validate"),
    )
    def validate(self):
        r = Reponse(demande=self)
        r.save()

    def est_provisionne(self):
        if (
            self.reponse.effectifs_provisionnes
            and self.reponse.logistique_provisionnes
            and self.reponse.subsistances_provisionnes
            and self.reponse.vehicules_provisionnes
        ):
            return True
        return False

    @transition(
        field=etat, source="valide", target="provisionne", conditions=[est_provisionne]
    )
    def provisionne(self):
        pass

    @transition(field=etat, source="cree", target="refuse")
    def refuse(self):
        pass

    @transition(
        field=etat,
        source="provisionne",
        target="cloture",
        permission=lambda instance, user: user.hasPerm("CoronApp.can_cloture"),
    )
    def cloture(self):
        ret = Retour(demande=self)
        ret.save()

    @transition(field=etat, source="cloture", target="termine")
    def termine(self):
        pass

    @transition(field=etat, source=["termine", "cloture", "refuse"], target="archive")
    def archive(self):
        pass

    def has_retour_spe(self):
        """ Seuls quelques types de mission n'ont pas de retour spéciique, cette fonction sert pour le template
        et retourne vrai si la demande a une retour spécifique
        """

        return self.type not in [
            "non_defini",
            "continuite",
            "accueil_ecoute",
            "soutien_op",
        ]

    def has_demande_spe(self):
        """ Idem du côté de la demande spécifique : 4 types ont des spécificités """
        return self.type in ["maraude", "aide_alim", "colis_urgence", "distribution"]

    def __str__(self):
        return "Demande " + self.titre

templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    {% load static %}
    <meta charset="UTF-8">

    <title>{% block title %} GestApp {% endblock %}</title>

    <link href="{% static "css/global.css" %}" rel="stylesheet">

    <!-- Bootstrap 4 + JQuery -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.0/umd/popper.min.js"
            integrity="sha256-FT/LokHAO3u6YAZv6/EKb7f2e0wXY3Ff/9Ww5NzT+Bk="
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>

    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
            integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

    <!-- DataTables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8"
            src="{% static "base.js" %}"></script>

    <link rel="icon" type="image/png" href="{% static "images/croix_rouge.jpeg" %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

        <!-- Logo Croix-Rouge -->
        <a class="navbar-brand" href="/">
            <img src="{% static "images/croix_rouge.jpeg" %}" width="60" height=60" alt="Logo Croix-Rouge">
        </a>

        <!-- Bouton mobile pour dérouler le menu -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Boutons de navigation -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/"> Accueil </a>
                </li>

                {% if request.user.is_authenticated %}
                    {% if perms.CoronApp.add_demande %}
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'demande-form' %}">Nouvelle demande </a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'demandes' %}">Gestion des demandes</a>
                    </li>


                {% else %}
                    <li class="nav-item">
                        <a class="nav-link " href="/accounts/login">Se connecter </a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    {% if perms.CoronApp.peut_importer %}
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'imports' %}">Imports</a>
                        </li>
                    {% endif %}

                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="/admin"><b>Administration</b></a>
                        </li>
                    {% endif %}
                    <li class="nav-item float-right" style="padding-left: 20px">
                        <a class="nav-link " href="/accounts/logout">Déconnexion <i class="fa fa-power-off"
                                                                                     aria-hidden="true"></i></a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </nav>
</header>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <link href="{% static "css/cover.css" %}" rel="stylesheet">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

        <main role="main" class="inner cover">
            <h1 class="cover-heading">GestApp</h1>
            <p class="lead">La GestApp a pour but de faciliter la gestion des activités de la Croix Rouge.
                Elle doit permettre de centraliser les demandes de mission ainsi que les affectations des bénévoles et
                du matériel.<br>

            </p>
            <div class="lead">
                {% if request.user.is_authenticated %}
                    {% if perms.CoronApp.add_demande %}
                        <a href="{% url 'demande-form' %}" class="btn btn-lg btn-secondary">Faire une demande</a>
                    {% endif %}
                    <a href="{% url 'demandes' %}" class="btn btn-lg btn-primary" style="float: right">Gérer les
                        demandes</a>
                {% else %}
                    <a href="/accounts/login" class="btn btn-lg btn-primary" style="float: right">Se connecter</a>
                {% endif %}
            </div>
        </main>
        <footer class="mastfoot mt-auto">
            <div class="inner">
                <p>Application pour la Croix-Rouge, par <a
                        href="https://gitlab.com/sia-insa-lyon">SIA INSA Lyon</a>
                    <br>
                    Version {{ version.major }}.{{ version.minor }}
                    <a href="https://gitlab.com/sia-insa-lyon/dev/dev-croix-rouge/-/blob/dev/CHANGELOG.md">Notes de
                        version</a></p>
            </div>
        </footer>
    </div>
{% endblock %}